ApiGatewayRestApiUri:
  Type: AWS::SSM::Parameter
  DependsOn:
    - ApiGatewayRestApi
  Properties:
    Name: /Test/CurrencyConverter/ApiGatewayUri
    Type: String
    Value: 
      !Join
        - ''
        - - "https://"
          - !Ref ApiGatewayRestApi
          - ".execute-api."
          - !Ref AWS::Region
          - ".amazonaws.com/${opt:stage}/"